#!/usr/bin/env python2

import sys

from map import Controller as C
from map import MapReader as MR
from map import Model as M
from map import MoveType as MT
from map import MVC

from greedy import Greedy
from lazy import Lazy
from quitter import Quitter
from swimmer import Swimmer


def main():
    f = open(sys.argv[1], "rt")
    map_reader = MR(f, sys.stdout)

    v = map_reader.get_view()
    MVC.Link(None, v, None)

    m = M(map_reader.raw_footer)
    MVC.Link(m, v, None)

    c = C()
    MVC.Link(m, v, c)

    # strategy bots
    greedy = Greedy(m, v)
    lazy = Lazy(m, v)
    quitter = Quitter(m, v)
    swimmer = Swimmer(m, v)

    print v

    while True:
        ch = sys.stdin.read(1)
        if ch == 'j':
            a = MT.LEFT
        elif ch == 'k':
            a = MT.DOWN
        elif ch == 'l':
            a = MT.RIGHT
        elif ch == 'i':
            a = MT.UP
        elif ch == 'w':
            a = MT.WAIT
        elif ch == 'a':
            a = MT.ABORT
        elif ch == '1':
            a = greedy.next_move()
        elif ch == '2':
            a = lazy.next_move()
        elif ch == '3':
            a = quitter.next_move()
        elif ch == '4':
            a = swimmer.next_move()
        else:
            continue
        print c.process(a)
        print v
        print m.current_score()
        print m.score_on_abort()
        print m.score_on_lift()


if __name__ == "__main__":
    main()
