#!/usr/bin/env python2

import sys
import time

from map import Controller as C
from map import MapReader as MR
from map import MoveType as MT
from map import MVC
from map import Model as M
from map import View as V
from greedy import Greedy as G

def main():
	f = open(sys.argv[1], "rt")
	map_reader = MR(f, sys.stdout)
	v = map_reader.get_view()
	print v

	MVC.Link(None, v, None)

	m = M(map_reader.raw_footer)

	MVC.Link(m, v, None)

	c = C()
	MVC.Link(m, v, c)

    # strategy init
	greedy = G()

	while(1):
		ch = sys.stdin.read(1)
		if ch == 'j':
			a = MT.LEFT
		elif ch == 'k':
			a = MT.DOWN
		elif ch == 'l':
			a = MT.RIGHT
		elif ch == 'i':
			a = MT.UP
		elif ch == 'w':
			a = MT.WAIT
		elif ch == 'a':
			a = MT.ABORT
		elif ch == '1': # execute greedy strategy
			a = greedy.next_move(m, v)
		else:
			continue
		print c.process(a)
		print v
		print m.current_score()
		print m.score_on_abort()
		print m.score_on_lift()

if __name__ == "__main__":
	main()
