#!/usr/bin/env python2

import sys
import time

from map import Controller as C
from map import MapReader as MR
from map import Model as M
from map import MoveType as MT
from map import MVC
from map import ResultType as RT
from map import View as V

def main():
    f = open(sys.argv[1], "rt")
    map_reader = MR(f, sys.stdout)

    v = map_reader.get_view()
    MVC.Link(None, v, None)

    m = M(map_reader.raw_footer)
    MVC.Link(m, v, None)

    c = C()
    MVC.Link(m, v, c)

    moves = open(sys.argv[2], "rt").readline()

    for ch in moves:
        if ch == 'L':
            a = MT.LEFT
        elif ch == 'D':
            a = MT.DOWN
        elif ch == 'R':
            a = MT.RIGHT
        elif ch == 'U':
            a = MT.UP
        elif ch == 'W':
            a = MT.WAIT
        elif ch == 'A':
            a = MT.ABORT
        else:
            continue
        res = c.process(a)
        if res == RT.OK:
            continue
        elif res == RT.ABORTED:
            print m.score_on_abort()
            return
        elif res == RT.DEAD:
            print str(m.current_score()) + " (DIED!)"
            return

    if m.has_reached_lift():
        print m.score_on_lift()
        return
    else:
        print m.score_on_abort()
        return



if __name__ == "__main__":
    main()
